
import Topnav from "./components/Topnav";
import Navbar from "./components/MainNav";

import "./globals.css";



export const metadata = {
  title: "Cartez Shop every thing Here",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >

      <Topnav/>
      <Navbar/>
      {children}</body>
    </html>
  );
}
